apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: irmepni2l-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/irmepni2l-java-springboot-gitops